#!/bin/bash

# top row
echo -e " \033[91m▄▄▄▄\033[0m   \033[92m▄▄▄▄\033[0m   \033[93m▄▄▄▄\033[0m   \033[94m▄▄▄▄\033[0m   \033[95m▄▄▄▄\033[0m   \033[96m▄▄▄▄\033[0m "

# extended top row if you want to make it taller
# uncomment the next 3 lines and change the second 1 to how many extra lines you want it to take
# for i in {1..1}: do
#   echo -e " \033[91m████\033[0m   \033[92m████\033[0m   \033[93m████\033[0m   \033[94m████\033[0m   \033[95m████\033[0m   \033[96m████\033[0m "
# done

# middle rows
# the screen shot looks like it has 3 middle rows, but if you want to make it
# taller or shorter try changing the 3  to any number 1 or greater
for i in {1..3}; do
  echo -e " \033[91m████\033[31m█\033[0m  \033[92m████\033[32m█\033[0m  \033[93m████\033[33m█\033[0m  \033[94m████\033[34m█\033[0m  \033[95m████\033[35m█\033[0m  \033[96m████\033[36m█\033[0m"
done

# extended bottom row if you want to make it taller
# uncomment the next 3 lines and change the second 1 to how many extra lines you want it to take
# for i in {1..1}: do
#   echo -e "  \033[31m████\033[0m   \033[32m████\033[0m   \033[33m████\033[0m   \033[34m████\033[0m   \033[35m████\033[0m   \033[36m████\033[0m"
# done

# bottom row
echo -e "  \033[31m▀▀▀▀\033[0m   \033[32m▀▀▀▀\033[0m   \033[33m▀▀▀▀\033[0m   \033[34m▀▀▀▀\033[0m   \033[35m▀▀▀▀\033[0m   \033[36m▀▀▀▀\033[0m"

# if you want to change the horizontal positioning, try to add or remove spaces to the
# beginning of each string, jsut add or remove the same amount, unless you want it too
# look all staggered and crazy

# if you want to make it wider then try copy/pasting to add more block charactes
# note that if you add x number of block characters in any section, you have to
# add the same number of block characters to that section in the other lines too
# unless you want a staggered uneven look

# ex if you add two more block charactes after \033[91m on the top row, then you should
# add two extra block characters after every other instance of \033[91m

# also remember the block character for the top row (▄) and the block character
# on the bottom row (▀), and the block character for the middle and extended top
# and extended bottom rows (█) are different

# if you don't know much about color codes but want to check out https://stackoverflow.com/a/75985833
